// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl5618D-xIWalUx3WnHPiJD3G2i-ZFIj0',
    appId: '1:346962283535:web:773943b5784769445d277a',
    messagingSenderId: '346962283535',
    projectId: 'demofirebase-a2721',
    authDomain: 'demofirebase-a2721.firebaseapp.com',
    storageBucket: 'demofirebase-a2721.firebasestorage.app',
    measurementId: 'G-5Q20LN1RFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwPovpEfZCDvXh7zF-rQQJKHqO7AjfbuE',
    appId: '1:346962283535:android:5eefb6e865d5c0725d277a',
    messagingSenderId: '346962283535',
    projectId: 'demofirebase-a2721',
    storageBucket: 'demofirebase-a2721.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA377BcKjwsLd9fmC2SZ9u4ZGGupe-DDWE',
    appId: '1:346962283535:ios:a2deb06edc9f68575d277a',
    messagingSenderId: '346962283535',
    projectId: 'demofirebase-a2721',
    storageBucket: 'demofirebase-a2721.firebasestorage.app',
    iosBundleId: 'com.flutter.base.stg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA377BcKjwsLd9fmC2SZ9u4ZGGupe-DDWE',
    appId: '1:346962283535:ios:c4e94e2e20387d2f5d277a',
    messagingSenderId: '346962283535',
    projectId: 'demofirebase-a2721',
    storageBucket: 'demofirebase-a2721.firebasestorage.app',
    iosBundleId: 'com.flutter.base',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl5618D-xIWalUx3WnHPiJD3G2i-ZFIj0',
    appId: '1:346962283535:web:0cc4d48cdb0b997e5d277a',
    messagingSenderId: '346962283535',
    projectId: 'demofirebase-a2721',
    authDomain: 'demofirebase-a2721.firebaseapp.com',
    storageBucket: 'demofirebase-a2721.firebasestorage.app',
    measurementId: 'G-E9VHYPL52S',
  );
}
