import 'dart:io';

/// 🎯 Script quét toàn bộ *_cubit.dart và *_bloc.dart có @injectable
/// Sinh ra BuildContext extensions tại:
///   lib/core/base/state/bloc/auto_bloc/bloc_extensions.g.dart
///
/// Chạy: dart scripts/generate_bloc_helper.dart
/// Hoặc: make bloc_gen

void main() {
  final pubspecFile = File('pubspec.yaml');
  if (!pubspecFile.existsSync()) {
    print('❌ pubspec.yaml not found. Run from project root.');
    return;
  }

  final pubspec = pubspecFile.readAsStringSync();
  final packageName = RegExp(
    r'^name:\s+([a-zA-Z0-9_]+)',
    multiLine: true,
  ).firstMatch(pubspec)?.group(1);

  if (packageName == null) {
    print('❌ Could not find package name in pubspec.yaml');
    return;
  }
  print('📦 Package: $packageName');

  final libDir = Directory('lib');
  if (!libDir.existsSync()) {
    print('❌ lib/ directory not found');
    return;
  }

  // ── Quét các file _cubit.dart và _bloc.dart ──
  final files =
      libDir.listSync(recursive: true).whereType<File>().where((f) {
          final p = f.path;
          return (p.endsWith('_cubit.dart') || p.endsWith('_bloc.dart')) &&
              !p.endsWith('.g.dart'); // bỏ qua generated files
        }).toList()
        ..sort((a, b) => a.path.compareTo(b.path)); // sort để output ổn định

  final entries = <_BlocEntry>[];

  for (final file in files) {
    final content = file.readAsStringSync();

    // Chỉ xử lý file có @injectable / @LazySingleton / @Singleton
    if (!content.contains('@injectable') &&
        !content.contains('@LazySingleton') &&
        !content.contains('@Singleton')) {
      continue;
    }

    // Tìm tất cả class extends (Bloc/Cubit) — bỏ qua dòng bị comment
    final matches = RegExp(
      r'^(?!\s*//).*\bclass\s+(\w+)\s+extends\s+(\w+)',
      multiLine: true,
    ).allMatches(content);

    for (final match in matches) {
      final className = match.group(1)!;
      final parentClass = match.group(2)!;

      // Bỏ qua Base classes và private classes
      if (className.startsWith('Base')) continue;
      if (className.startsWith('_')) continue;

      // Chỉ lấy classes extends *Bloc, *Cubit, BaseBloc, BaseCubit
      if (!parentClass.contains('Bloc') && !parentClass.contains('Cubit'))
        continue;

      // Chuẩn hóa path
      String relPath = file.path.replaceAll('\\', '/');
      final libIndex = relPath.indexOf('lib/');
      if (libIndex != -1) {
        relPath = relPath.substring(libIndex + 4);
      }

      final importPath = 'package:$packageName/$relPath';

      // Tìm feature name (lib/features/FEATURE_NAME/...)
      String? featureName;
      final parts = relPath.split('/');
      if (parts.contains('features')) {
        final fi = parts.indexOf('features');
        if (fi + 1 < parts.length) {
          featureName = parts[fi + 1];
        }
      }

      entries.add(
        _BlocEntry(
          className: className,
          importPath: importPath,
          featureName: featureName,
        ),
      );
    }
  }

  // ── Dedup: xóa entries trùng hoàn toàn (cùng className + importPath) ──
  final seen = <String>{};
  final dedupedEntries = entries.where((e) {
    final key = '${e.className}::${e.importPath}';
    return seen.add(key);
  }).toList();

  if (dedupedEntries.isEmpty) {
    print('⚠️ No @injectable Blocs/Cubits found');
    return;
  }

  // ── Xử lý trùng tên class (còn lại sau dedup) ──
  final classCount = <String, int>{};
  for (final e in dedupedEntries) {
    classCount[e.className] = (classCount[e.className] ?? 0) + 1;
  }

  // Khi có trùng tên class -> nối feature/sub-feature path vào method name
  final usedMethodNames = <String>{};

  for (final e in dedupedEntries) {
    String methodName = _classToMethodName(e.className);

    if (classCount[e.className]! > 1) {
      // Nối đường dẫn feature vào tên để phân biệt
      final parts = e.importPath.split('/');
      final presIdx = parts.indexOf('presentation');
      if (presIdx >= 2) {
        // Ưu tiên lấy thư mục sub-feature ngay trước 'presentation'
        final featureFolder = parts[presIdx - 1];
        methodName = _snakeToCamel(featureFolder) + e.className;
        methodName = methodName[0].toLowerCase() + methodName.substring(1);
      } else if (e.featureName != null) {
        methodName = _snakeToCamel(e.featureName!) + e.className;
        methodName = methodName[0].toLowerCase() + methodName.substring(1);
      }
    }

    // Đảm bảo không trùng method name (fallback counter)
    final originalMethod = methodName;
    var counter = 2;
    while (usedMethodNames.contains(methodName)) {
      methodName = '$originalMethod$counter';
      counter++;
    }
    usedMethodNames.add(methodName);
    e.methodName = methodName;
  }

  // ── Sinh code ──
  final buffer = StringBuffer();
  buffer.writeln('// ⚡ GENERATED CODE - DO NOT MODIFY BY HAND');
  buffer.writeln('// Generated by: dart scripts/generate_bloc_helper.dart');
  buffer.writeln('// Generated at: ${DateTime.now().toIso8601String()}');
  buffer.writeln('// Total: ${dedupedEntries.length} blocs/cubits');
  buffer.writeln('// ignore_for_file: unused_import');
  buffer.writeln();
  buffer.writeln("import 'package:flutter/widgets.dart';");
  buffer.writeln("import 'package:flutter_bloc/flutter_bloc.dart';");
  buffer.writeln(
    "import 'package:$packageName/core/base/state/bloc/auto_bloc/bloc_manager.dart';",
  );
  buffer.writeln();

  // Imports (sorted, unique)
  final sortedImports = dedupedEntries.map((e) => e.importPath).toSet().toList()
    ..sort();
  for (final imp in sortedImports) {
    buffer.writeln("import '$imp';");
  }

  buffer.writeln();
  buffer.writeln(
    '/// Extension tự sinh — truy cập BLoC/Cubit nhanh qua context',
  );
  buffer.writeln('/// Ưu tiên: BlocManager cache → BlocProvider trong tree');
  buffer.writeln('extension BlocContextX on BuildContext {');

  for (final e in dedupedEntries) {
    buffer.writeln(
      '  ${e.className} get ${e.methodName} => '
      'BlocManager.peek<${e.className}>() ?? read<${e.className}>();',
    );
  }

  buffer.writeln('}');

  // ── Ghi file ──
  const outputPath = 'lib/gen/bloc/bloc_extensions.g.dart';
  final outputFile = File(outputPath);
  if (!outputFile.parent.existsSync()) {
    outputFile.parent.createSync(recursive: true);
  }
  outputFile.writeAsStringSync(buffer.toString());
  print('✅ Generated ${dedupedEntries.length} extensions → $outputPath');
  for (final e in dedupedEntries) {
    print('   context.${e.methodName} → ${e.className}');
  }
}

// ── Helpers ──

class _BlocEntry {
  final String className;
  final String importPath;
  final String? featureName;
  String methodName = '';

  _BlocEntry({
    required this.className,
    required this.importPath,
    this.featureName,
  });
}

String _classToMethodName(String className) {
  return className[0].toLowerCase() + className.substring(1);
}

String _snakeToCamel(String snake) {
  return snake
      .split('_')
      .map((e) => e.isEmpty ? '' : e[0].toUpperCase() + e.substring(1))
      .join('');
}
